### Test POST Request
POST http://localhost:3000/api/requests
Content-Type: application/json

{
  "name": "Don",
  "address": "123 Something Road",
  "browse": "Koala",
  "animalQuantity": 12
}

### Test GET Request
GET http://localhost:3000/api/requests
Content-Type: application/json